deploy script alteration

diff --git a/.github/workflows/ios_deploy.yml b/.github/workflows/ios_deploy.yml
--- a/.github/workflows/ios_deploy.yml
+++ b/.github/workflows/ios_deploy.yml
@@ -29,13 +29,7 @@ jobs:
         run: |
           brew install flutter
 
-      - name: Install dependencies
-        run: |
-          brew install node
-          npm install -g yarn
-          yarn install
-
-      - name: Flutter pub get
+       - name: Flutter pub get
         run: flutter pub get
 
       - name: Prepare for Flutter build
@@ -44,11 +38,22 @@ jobs:
           flutter clean
           flutter build ios --release --no-codesign --verbose
 
-      - name: Install and setup CocoaPods
+      - name: Check Generated.xcconfig exists
+        run: |
+          if [ ! -f ios/Flutter/Generated.xcconfig ]; then
+            echo "Generated.xcconfig does not exist, ensure Flutter build is successful and generates required files."
+            exit 1
+          fi
+
+      - name: Install CocoaPods
         run: |
           sudo gem install cocoapods
           pod setup
+
+      - name: Update and install CocoaPods
+        run: |
           cd ios
+          pod repo update
           pod install
           cd ..
 
